#!/data/data/com.termux/files/usr/bin/bash
##################################################
## alephalpha0  |   Sync website dir to phone.  ##
## created:2020-10-19   |  modified:2020-10-30  ##
##----------------------------------------------##
##        https://github.com/alephalpha0        ##
##            http://rootofpi.me                ##
####################           ###################
#############                        #############
## Many thanks to those who have shared and     ##
## discussed their dotfiles/source code/scripts ## 
## on blogs, stackoverflow, dev.to, gitlab /    ##
## github, and any open forum for ideas on the  ##
##  world wide web. I am continually learning   ##
## and discovering new things because of you.   ##
##################################################
## There is no LICENSE attached to this file.   ##
##     I require no attribute for its use.      ##
## Do what thou will. That's the whole of law.  ##
##----------------------------------------------##
##!!!!!!!!!!NO WARRANTY PROVIDED FOR!!!!!!!!!!!!##
##!!!!!!!!!!!ANY POSSIBLE USE EITHER!!!!!!!!!!!!##
##################################################
## Script has one function: cd into my website's 
## dir and copy the entirety of it via rsync into
## my phone's internal storage. Redundant back up
## for the win! 

##################################################
# Gracefully exit on error like a lady.
likeALady() {
	echo "That dir does not appear in our time line."
	return
}

main() {
	local termuxPath=~/rootofpi.me/
	local phonePath=~/storage/shared/rootofpi.me
    if [ -d "${termuxPath}" ]
    then
    
	  if [ "${termuxPath}" -nt "${phonePath}" ]
	  then
	    rsync -avz --checksum --progress -h \
	    "${termuxPath}" "${phonePath}"
	  else
	    echo "Seems the directories are already in sync."
	    exit
	  fi

	else
	  echo "Your main ROP directory isn't there. \
	  What's wrong?"
	  exit
	fi  
}
main
