#!/bin/sh
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#   termux-file-editor ||    Save or edit a shared file.    #
#    created:2020-11-26      ||     modified:2020-11-26     #
# product of alephalpha0's mind || alephalpha0@tutanota.com #
# \\\\\\\\\\\\\\\\\ A ROOTOFPI PRODUCTION ///////////////// #
#  http://github.com/alephalpha0       http://rootofpi.me   #
#########################         ###########################
##################                       ####################
# Many thanks to those who have shared and discussed their  #
# dotfiles/source code/scripts on blogs, stackoverflow,     #
# dev.to, gitlab / github, and any open forum for ideas on  #
# the world wide web. I am continually learning and finding #
# new things because of you.                                #
#############################################################
#############################################################
# termux-url-opener | tui to download URLs passed to it into file.
# Copyright (C) 2020 alephalpha0

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### SCRIPT VARIABLES
#sets the file being passed in.
file="${1}"
## fun terminal colors!
# background color using ANSI escape    
bgBlack=$(tput setab 0) # black
bgRed=$(tput setab 1) # red
bgGreen=$(tput setab 2) # green
bgYellow=$(tput setab 3) # yellow
bgBlue=$(tput setab 4) # blue
bgMagenta=$(tput setab 5) # magenta
bgCyan=$(tput setab 6) # cyan
bgWhite=$(tput setab 7) # white
# foreground color using ANSI escape
fgBlack=$(tput setaf 0) # black
fgRed=$(tput setaf 1) # red
fgGreen=$(tput setaf 2) # green
fgYellow=$(tput setaf 3) # yellow
fgBlue=$(tput setaf 4) # blue
fgMagenta=$(tput setaf 5) # magenta
fgCyan=$(tput setaf 6) # cyan
fgWhite=$(tput setaf 7) # white
# text editing options
txBold=$(tput bold)   # bold
txHalf=$(tput dim)    # half-bright
txUnderline=$(tput smul)   # underline
txEndUnder=$(tput rmul)   # exit underline
txReverse=$(tput rev)    # reverse
txStandout=$(tput smso)   # standout
txEndStand=$(tput rmso)   # exit standout
txReset=$(tput sgr0)   # reset attributes

#menu repetitions.
lineplus="${bgBlue}${fgBlack}\
	+++++++++++++++++++++++++++++++++++++++++++++++\
	${txReset}"
	
if [[ -z "${file}" ]]; then
  echo "I've been given nothing to work with."
  return 1
fi

lineplus()
echo "${txBold}${txUnderline}${bgBlue}${fgBlack}\
alephalpha0's Termux File Editor Selection Menu${txReset}"
lineplus()
lineplus()
echo "${txBold}${txUnderline}${bgBlue}${fgBlack}\
Chose an option below. (1) is default."
lineplus()
echo "1) Download file into Termux FS."
echo "2) Open up file with Micro for editing."
read -r -p "Option:" selection
while [[ $selection -gt 2]]
do
  read -r -p "Please input correct option:" selection
done
case "$selection" in
1)
  wget -c --show-progress "${file}"
  return 0
  ;;
2)
  $EDITOR "${file}"
  return 0
  ;;
*)
  return 1
  ;;
esac
