#!/data/data/com.termux/files/usr/bin/bash
##################################################
## alephalpha0  |  Download files passed to me. ##
## created:2020-10-20   |  modified:2020-10-31  ##
##----------------------------------------------##
##        https://github.com/alephalpha0        ##
##            http://rootofpi.me                ##
####################           ###################
#############                        #############
## Many thanks to those who have shared and     ##
## discussed their dotfiles/source code/scripts ## 
## on blogs, stackoverflow, dev.to, gitlab /    ##
## github, and any open forum for ideas on the  ##
##  world wide web. I am continually learning   ##
## and discovering new things because of you.   ##
##################################################
## There is no LICENSE attached to this file.   ##
##     I require no attribute for its use.      ##
## Do what thou will. That's the whole of law.  ##
##----------------------------------------------##
##!!!!!!!!!!NO WARRANTY PROVIDED FOR!!!!!!!!!!!!##
##!!!!!!!!!!!ANY POSSIBLE USE EITHER!!!!!!!!!!!!##
##################################################
# Script takes urls passed to it and downloads the 
# playlist, video, file or page to ~/downloads/*. 
#
# I'm using it as the script termux uses when a url
# is passed to it from amother app.
#
# Trying to preempt myself and guess my general 
# reasons for sharing to termux. Main use in my 
# eyes is downloading raw files from github,
# and downloading videos from youtube.. 
###########################################################

###TODO
# Pretty up the script.
# Add more cases to url options.
# Make it command-line ready?

### SCRIPT VARIABLES
#sets URL to the url shared/passed to termux
readonly ARGS=( "${@}" )
readonly URL=${ARGS[1]}

##################################################
# Gracefully exit on error like a lady.
likeALady() {
	echo "That dir does not appear in our time line."
	return
}


##################################################
# Two-step tussle to figure out if the dir exists. 
# if not mkdir & cd into dir, if so just cd into it.
dirExists() {
    #the subdirectory we are checking.
	local silkMouth="${1}"

	if [ -d ~/downloads/"${silkMouth}" ]
	then
	    cd ~/downloads/"${silkMouth}" || likeALady
	else
	    mkdir ~/downloads/"${silkMouth}"
	    cd ~/downloads/"${silkMouth}" || likeALady
	fi
}


main(){
# the base download dir
local DIR=~/downloads/

##################################################
# Main logic block. First will check that we 
# didn't accidentally get passed an empty string. 
# If so, we exit, hopefully gracefully like a lady.
if [ -z "${URL}" ]; then
    echo "You've passed an empty string to the script. "
    exit
else
##################################################
# Logic train using case on URL parts to see how 
# to handle downloading.
    case ${URL} in
    
    *playlist*) #check if url is a youtube playlist
        dirExists music #check ${DIR}/music exists & cd
        youtube-dl --extract-audio --audio-format mp3 \
        --audio-quality 0 \
        -o "%(playlist_title)s/%(playlist_index)02d-%(title)s.%(ext)s" \
        "${URL}"
    ;;
         
    *youtube*|*youtu.be*) #check if url is youtube, phase 1
        dirExists videos #check ${DIR}/videos exists &cd 
        youtube-dl -o "%(title)s.%(ext)s" "${URL}"
    ;;
            
    *github*) #check if url is github.
        cd "${DIR}" || likeALady
        wget --show-progress "${URL}" 
    ;;
      
    *.tar.bz2*|*.txt*|*.html*) # getting an archive file from the web
        cd "${DIR}" || likeALady
        wget --show-progress "${URL}" 
    ;;
      
    *pornhub*) # yeah so what?
        dirExists porn # does ${DIR}/porn exist?
        youtube-dl "${URL}"
    ;;
      
    *blog*)
        cd "${DIR}" || likeALady
        wget --adjust-extension --span-hosts --convert-links --backup-converted --page-requisites "${URL}" 
    ;;
      
    *)
        echo "I'm not sure what you want me to do here..."
    ;;
    esac
fi
}
main
